"""Add profile fields and UserGoal table

Revision ID: 153dde26cc88
Revises: 051a806efaa6
Create Date: 2025-11-12 17:39:14.578439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153dde26cc88'
down_revision = '051a806efaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(length=255), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_weight_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('target_weight_kg')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('gender')

    op.drop_table('user_goals')
    # ### end Alembic commands ###
