"""Add start_date column to plans table

Revision ID: 18630a849ba9
Revises: 153dde26cc88
Create Date: 2025-11-12 17:55:34.836891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '18630a849ba9'
down_revision = '153dde26cc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:

        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))


    op.execute(
        sa.update(sa.table(
            'plans', sa.column('start_date', sa.Date())
        )).values(start_date=func.current_date())
    )

    with op.batch_alter_table('plans', schema=None) as batch_op:

        batch_op.alter_column('start_date', existing_type=sa.Date(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
