"""create tips table

Revision ID: 38083713f2c9
Revises: 683025366e56
Create Date: 2025-11-18 17:54:31.496634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38083713f2c9'
down_revision = '683025366e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tips')
    # ### end Alembic commands ###
