"""Add age field to User

Revision ID: 683025366e56
Revises: 18630a849ba9
Create Date: 2025-11-15 10:06:48.271127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683025366e56'
down_revision = '18630a849ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
